stages:
    data_ingestion:
      cmd: python src/data_ingestion.py
      deps:
        - src/data_ingestion.py
      outs:
        - data/raw
    data_preprocessing:
      cmd: python src/data_preprocessing.py
      deps:
        - src/data_preprocessing.py
        - data/raw
      outs:
        - data/interim
    feature_engineering:
      cmd: python src/feature_engineering.py
      deps:
        - src/feature_engineering.py
        - data/interim
      outs:
        - data/processed
    model_training:
      cmd: python src/model_training.py
      deps:
        - src/model_training.py
        - data/processed
      outs:
        - models/random_forest_model.pkl
    model_evaluation:
      cmd: python src/model_evaluation.py
      deps:
        - src/model_evaluation.py
        - models/random_forest_model.pkl
      outs:
        - reports/metrics.json
# metrics:
#   - dvclive/metrics.json
# plots:
#   - dvclive/plots/metrics:
#       x: step 
# params:
#   - dvclive/params.yaml
